---
- import_tasks: setup.yml

- name: Copy Kibana configuration.
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: root
    mode: 0644
  notify: restart kibana

- name: Ensure Kibana is started and enabled at boot.
  systemd:
    name: kibana
    state: started
    enabled: "{{ kibana_enabled_on_boot }}"
    daemon_reload: yes

- name: Check if X-Pack installed.
  stat:
    path: /usr/share/kibana/plugins/x-pack
  register: xpack_dir
  when: kibana_xpack_enabled

- name: Remove installed X-Pack.
  become: true
  command: /usr/share/kibana/bin/kibana-plugin remove x-pack
  when:
    - kibana_xpack_enabled
    - xpack_dir.stat.exists

- name: Install X-Pack.
  become: true
  command: /usr/share/kibana/bin/kibana-plugin install x-pack
  when: kibana_xpack_enabled
  notify: restart kibana
